import RevealOnScroll from "./reveal-on-scroll";

export default function Home() {
  return (
    <>
<header className="shell topbar"><a className="brand" href="#inicio" aria-label="Rhayvene Oliveira, início"><span className="brand-mark">R</span><span>RHAYVENE OLIVEIRA<small>ARQUITETURA & INTERIORES</small></span></a><nav className="nav" aria-label="Navegação principal"><a href="#sobre">O estúdio</a><a href="#inspiracoes">Inspirações</a><a href="#processo">Processo</a><a className="nav-cta" href="#contato">Conversar ↗</a></nav></header>
<main id="inicio"><section className="hero shell"><div className="eyebrow">Arquitetura com intenção &nbsp; / &nbsp; Arquitetura & interiores</div><div className="hero-heading"><h1>Espaços<br /><span className="outline">para viver.</span></h1><p className="hero-aside"><i />Uma arquitetura que acolhe a rotina, valoriza os detalhes e encontra beleza no essencial.</p></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1800&q=85" alt="Ambiente residencial contemporâneo com materiais naturais" fetchPriority="high" /><div className="hero-caption">Luz, matéria, proporção</div><div className="hero-index">01 / 03</div></div><div className="hero-scroll"><span>Role para explorar</span><span aria-hidden="true">↓</span></div></section>
<section id="sobre" className="section shell intro-grid"><div className="section-head reveal"><span className="section-num">01 / Sobre Rhayvene</span><h2>Uma forma<br />de sentir.</h2></div><div className="intro-copy reveal"><p>Para Rhayvene Oliveira, cada espaço começa com uma conversa. Cada projeto começa pela escuta e ganha forma na maneira única de viver de quem o habita.</p><p className="small">Do primeiro esboço à escolha dos materiais, o trabalho busca equilíbrio entre função, sensibilidade e tempo. Ambientes que fazem sentido hoje e continuam fazendo amanhã.</p><a href="#processo" className="text-link">Conheça o processo <span aria-hidden="true">↗</span></a></div></section>
<section id="inspiracoes" className="projects"><div className="shell"><div className="section-head reveal"><div><span className="section-num">02 / Referências</span><h2>Atmosferas<br />que inspiram.</h2></div><p className="muted">Uma seleção de ambientes residenciais e interiores para mostrar materiais, luz e proporções. Imagens ilustrativas; consulte o catálogo de Rhayvene para conhecer projetos realizados.</p></div><div className="project-grid"><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=85" alt="Sala contemporânea com texturas naturais" /></div><div className="project-meta"><h3>Texturas e silêncio</h3><span>Interiores / 01</span></div></article><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1000&q=85" alt="Espaço residencial luminoso e contemporâneo" /></div><div className="project-meta"><h3>Luz como matéria</h3><span>Residencial / 02</span></div></article><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1500&q=85" alt="Ambiente arquitetônico com linhas limpas" /></div><div className="project-meta"><h3>O essencial permanece</h3><span>Conceito / 03</span></div></article></div></div></section>
<section id="processo" className="section shell approach"><div className="reveal"><span className="section-num">03 / Processo</span><h2>Do diálogo<br />ao detalhe.</h2></div><div className="steps"><div className="step reveal"><strong>01</strong><div><h3>Escuta</h3><p>Conversamos sobre a rotina, as necessidades e o que você imagina para o seu espaço.</p></div></div><div className="step reveal"><strong>02</strong><div><h3>Concepção</h3><p>Transformamos suas ideias em possibilidades de layout, materiais e atmosfera.</p></div></div><div className="step reveal"><strong>03</strong><div><h3>Desenvolvimento</h3><p>Detalhamos as soluções para que cada decisão tenha clareza e propósito.</p></div></div><div className="step reveal"><strong>04</strong><div><h3>Realização</h3><p>Acompanhamos o caminho do projeto para aproximar o resultado da intenção original.</p></div></div></div></section>
<section id="contato" className="contact"><div className="shell"><div className="eyebrow reveal">04 / Seu próximo espaço</div><h2 className="reveal">Vamos imaginar<br /><em>o que vem depois?</em></h2><div className="contact-note reveal"><p>Atendimento somente com hora marcada. Conte sua ideia pelo WhatsApp ou ligue para +55 11 98215-4738.</p><a className="contact-button" href="https://wa.me/5511982154738?text=Ol%C3%A1%2C%20Rhayvene%21%20Gostaria%20de%20conversar%20sobre%20um%20projeto." aria-label="Conversar com Rhayvene pelo WhatsApp" target="_blank" rel="noopener noreferrer">↗</a></div><footer className="footer"><span>© 2026 Rhayvene Oliveira</span><span>Arquitetura & interiores</span><a href="tel:+5511982154738">+55 11 98215-4738 ↗</a></footer></div></section></main>
      <RevealOnScroll />
    </>
  );
}
