import RevealOnScroll from "./reveal-on-scroll";

export default function Home() {
  return (
    <>
<header className="shell topbar"><a className="brand" href="#inicio" aria-label="Ateliê Forma, início"><span className="brand-mark">A</span><span>ATELIÊ FORMA<small>ARQUITETURA & INTERIORES</small></span></a><nav className="nav" aria-label="Navegação principal"><a href="#sobre">O estúdio</a><a href="#inspiracoes">Inspirações</a><a href="#processo">Processo</a><a className="nav-cta" href="#contato">Fale com a arquiteta ↗</a></nav></header>
<main id="inicio"><section className="hero shell"><div className="eyebrow">Arquitetura com intenção &nbsp; / &nbsp; 01 — 04</div><div className="hero-heading"><h1>Espaços<br /><span className="outline">para viver.</span></h1><p className="hero-aside"><i />Uma arquitetura que acolhe a rotina, valoriza os detalhes e encontra beleza no essencial.</p></div><div className="hero-photo"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1800&q=85" alt="Ambiente residencial contemporâneo com materiais naturais" fetchPriority="high" /><div className="hero-caption">Luz, matéria, proporção</div><div className="hero-index">01 / 03</div></div><div className="hero-scroll"><span>Role para explorar</span><span aria-hidden="true">↓</span></div></section>
<section id="sobre" className="section shell intro-grid"><div className="section-head reveal"><span className="section-num">01 / Sobre o estúdio</span><h2>Uma forma<br />de sentir.</h2></div><div className="intro-copy reveal"><p>Antes de desenhar paredes, entendemos pessoas. Cada projeto começa pela escuta e ganha forma na maneira única de viver de quem o habita.</p><p className="small">Do primeiro esboço à escolha dos materiais, buscamos equilíbrio entre função, sensibilidade e tempo. Ambientes que fazem sentido hoje e continuam fazendo amanhã.</p><a href="#processo" className="text-link">Conheça o processo <span aria-hidden="true">↗</span></a></div></section>
<section id="inspiracoes" className="projects"><div className="shell"><div className="section-head reveal"><div><span className="section-num">02 / Inspirações</span><h2>Atmosferas<br />que inspiram.</h2></div><p className="muted">Referências visuais de materiais, luz e espaços que traduzem nosso olhar. Imagens ilustrativas.</p></div><div className="project-grid"><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=85" alt="Sala contemporânea com texturas naturais" /></div><div className="project-meta"><h3>Texturas e silêncio</h3><span>Interiores / 01</span></div></article><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1000&q=85" alt="Espaço residencial luminoso e contemporâneo" /></div><div className="project-meta"><h3>Luz como matéria</h3><span>Residencial / 02</span></div></article><article className="project-card reveal"><div className="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1500&q=85" alt="Ambiente arquitetônico com linhas limpas" /></div><div className="project-meta"><h3>O essencial permanece</h3><span>Conceito / 03</span></div></article></div></div></section>
<section id="processo" className="section shell approach"><div className="reveal"><span className="section-num">03 / Nosso processo</span><h2>Do diálogo<br />ao detalhe.</h2></div><div className="steps"><div className="step reveal"><strong>01</strong><div><h3>Escuta</h3><p>Conversamos sobre a rotina, as necessidades e o que você imagina para o seu espaço.</p></div></div><div className="step reveal"><strong>02</strong><div><h3>Concepção</h3><p>Transformamos suas ideias em possibilidades de layout, materiais e atmosfera.</p></div></div><div className="step reveal"><strong>03</strong><div><h3>Desenvolvimento</h3><p>Detalhamos as soluções para que cada decisão tenha clareza e propósito.</p></div></div><div className="step reveal"><strong>04</strong><div><h3>Realização</h3><p>Acompanhamos o caminho do projeto para aproximar o resultado da intenção original.</p></div></div></div></section>
<section id="contato" className="contact"><div className="shell"><div className="eyebrow reveal">04 / Seu próximo espaço</div><h2 className="reveal">Vamos imaginar<br /><em>o que vem depois?</em></h2><div className="contact-note reveal"><p>Conte sua ideia. O primeiro passo de um bom projeto é uma boa conversa.</p><a className="contact-button" href="mailto:contato@exemplo.com?subject=Quero%20conversar%20sobre%20um%20projeto" aria-label="Enviar e-mail para conversar sobre um projeto">↗</a></div><footer className="footer"><span>© 2026 Ateliê Forma</span><span>Arquitetura & interiores</span><a href="mailto:contato@exemplo.com">Entrar em contato ↗</a></footer></div></section></main>
      <RevealOnScroll />
    </>
  );
}
